In [18]:
import numpy as np
A = np.array([ [4. ,-1. , 0. ,-1. ,0. ,0. ,0. ,0. ,0. ], 
               [-1. ,4. ,-1. , 0. ,-1. ,0. ,0. ,0. ,0. ], 
               [0. ,-1. ,4. ,0. , 0. ,-1. ,0. ,0. ,0. ],
               [-1. ,0. ,0. ,4. ,-1. , 0. ,-1. ,0. ,0. ],
               [0. ,-1. ,0. ,-1. ,4. ,-1. ,0. ,-1. ,0.],
               [0. ,0. ,-1. ,0. ,-1. ,4. ,0. ,0. ,-1. ],
               [0. ,0. ,0. ,-1. ,0. ,0. ,4. ,-1. ,0. ],
               [0. ,0. ,0. ,0. ,-1. ,0. ,-1. ,4. ,-1. ],
               [0. ,0. ,0. ,0. ,0. ,-1. ,0. ,-1. ,4. ], ])

b = np.array([ [4.],   
               [-1.],  
               [-5.],
               [-2.],
               [2.],
               [2.],
               [-1.],
               [1.],
               [6.] ]) 

C = np.concatenate((A,b), axis = 1)  # Επαυξημένος πίνακας

In [19]:
# Επίλυση ερωτήματος β με χρήση της μεθόδου απαλοιφής Gauss με χρήση μερικής οδήγησης

print('Ξεκινά η επίλυση με μέθοδο απαλοιφής Gauss με χρήση μερικής οδήγησης \n')
isSolvable = True  
for row in range(C.shape[0]):
  col = row   
  pivotRow = row + np.argmax(abs(C[row:, col]))  
  C[[row, pivotRow]] = C[[pivotRow, row]]  # Εδώ γίνεται η εναλλαγή γραμμών
  pivotEle = C[row , col]  # Εδώ ορίζεται το στοιχείο οδηγός
  if pivotEle == 0: # Αν το στοιχείο οδηγός είναι μηδενικό τότε το σύστημα δεν επιλύεται
    print('Το σύστημα δεν επιλύεται')
    isSolvable = False
    break
  else:   
    for r in range(row+1, C.shape[0] ):
      m =  - (C[r,col] / pivotEle) 
      C[r] = C[r] + m*C[row] 

if(isSolvable):
  print('Ο πίνακάς μας έχει έρθει σε άνω διαγώνια μορφή \n', C)
  print('Ορίζω το διάνυσμα της λύσης και το αρχικοποιώ να έχει το σχήμα του C με μηδενικά στοιχεία')
  X = np.array([[0.] for ii in range(C.shape[0])]) 
  print(X)

  # Εδώ γίνεται η πίσω αντικατάσταση
  for ii in reversed(range(len(X))): 
    X[ii] = ( C[ii,-1] - C[ii][:-1]@(X) ) / C[ii,ii]

  print('Η λύση βρίσκεται να είναι \n', X)
  print('Επαληθεύουμε τη λύση')
  print('A X - b = \n', A@X - b )

Ξεκινά η επίλυση με μέθοδο απαλοιφής Gauss με χρήση μερικής οδήγησης 

Ο πίνακάς μας έχει έρθει σε άνω διαγώνια μορφή 
 [[ 4.         -1.          0.         -1.          0.          0.
   0.          0.          0.          4.        ]
 [ 0.          3.75       -1.         -0.25       -1.          0.
   0.          0.          0.          0.        ]
 [ 0.          0.          3.73333333 -0.06666667 -0.26666667 -1.
   0.          0.          0.         -5.        ]
 [ 0.          0.          0.          3.73214286 -1.07142857 -0.01785714
  -1.          0.          0.         -1.08928571]
 [ 0.          0.          0.          0.          3.40669856 -1.07655502
  -0.28708134 -1.          0.          1.33014354]
 [ 0.          0.          0.          0.          0.          3.39185393
  -0.09550562 -0.31601124 -1.          1.0758427 ]
 [ 0.          0.          0.          0.          0.          0.
   3.70517598 -1.0931677  -0.02815735 -1.1494824 ]
 [ 0.          0.          0.        

In [20]:
# Επίλυση ερωτήματος β με χρήση της μεθόδου LU

# Παραγοντοποίηση του Α σε L και U
print('Ξεκινάμε την παραγοντοποίηση LU \n')
(n,m) = A.shape
if n != m: print('Ο πίνακας Α δεν είναι τετραγωνικός')

# Σχηματισμός των U, L
U = A.copy()  # Αυτό δεν είναι απαραίτητο, είναι πιο αποδοτικό να αποθηκεύονται οι L, U εντός του Α
L = np.identity(A.shape[0])

print('Αρχικοποίηση του πίνακα U σε \n', U)
print('Αρχικοποίηση του πίνακα L σε \n', L)

for k in range(n-1):
    for j in range(k+1,n):
        L[j,k] = U[j,k] / U[k,k]
        U[j,k:n] = U[j,k:n] - L[j,k]*U[k,k:n]

print('Τελική μορφή του L \n', L)
print('Τελική μορφή του U \n', U)

print('Επαληθεύουμε ότι ο LU-A είναι ο μηδενικός πίνακας \n', L@U - A)

# Εμπρός αντικατάσταση (Ly=x)

C = np.concatenate((L,b), axis = 1)
print('Παίρνουμε τον επαυξημένο του U \n', C)
print('Ορίζω το διάνυσμα της λύσης και το αρχικοποιώ να έχει το σχήμα του C (επαυξημένου) με μηδενικά στοιχεία')
Y = np.array([[0.] for ii in range(C.shape[0])]) 
print(Y)

# Εδώ γίνεται η πίσω αντικατάσταση
for ii in range(len(Y)): 
    Y[ii] = ( C[ii,-1] - C[ii][:-1]@(Y) ) / C[ii,ii]

print('Η λύση βρίσκεται να είναι \n', Y)


# Πίσω αντικατάσταση (Ux=y)

D = np.concatenate((U,Y), axis = 1)
print('Παίρνουμε τον επαυξημένο του U \n', D)
print('Ορίζω το διάνυσμα της λύσης και το αρχικοποιώ να έχει το σχήμα του D (επαυξημένου) με μηδενικά στοιχεία')
X = np.array([[0.] for ii in range(D.shape[0])]) 
print(X)

# Εδώ γίνεται η πίσω αντικατάσταση
for ii in reversed(range(len(X))): 
    X[ii] = ( D[ii,-1] - D[ii][:-1]@(X) ) / D[ii,ii]

print('Η λύση βρίσκεται να είναι \n', X)
print('Επαληθεύουμε τη λύση')
print('U X - Y = \n', U@X - Y )

Ξεκινάμε την παραγοντοποίηση LU 

Αρχικοποίηση του πίνακα U σε 
 [[ 4. -1.  0. -1.  0.  0.  0.  0.  0.]
 [-1.  4. -1.  0. -1.  0.  0.  0.  0.]
 [ 0. -1.  4.  0.  0. -1.  0.  0.  0.]
 [-1.  0.  0.  4. -1.  0. -1.  0.  0.]
 [ 0. -1.  0. -1.  4. -1.  0. -1.  0.]
 [ 0.  0. -1.  0. -1.  4.  0.  0. -1.]
 [ 0.  0.  0. -1.  0.  0.  4. -1.  0.]
 [ 0.  0.  0.  0. -1.  0. -1.  4. -1.]
 [ 0.  0.  0.  0.  0. -1.  0. -1.  4.]]
Αρχικοποίηση του πίνακα L σε 
 [[1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1.]]
Τελική μορφή του L 
 [[ 1.          0.          0.          0.          0.          0.
   0.          0.          0.        ]
 [-0.25        1.          0.          0.          0.          0.
   0.          0.          0.        ]
 [ 0.         -0.26666667  1.          0.         