In [2]:
import numpy as np

A = np.array([ [1. ,2. , 1. ], 
               [2. ,2. , 3. ], 
               [-1., -3., 0.] ])

b = np.array([ [0.],   # note the format of np.array([ ])
               [3.],   # np.array([ [0], [3], [2] ]) has shape 3 x 1 (πίνακας στήλη)
               [2.] ]) # while np.array([[ 0, 3, 2 ]) would have 1 x 3 (πίνακας γραμμή)

In [3]:
(n, m) = A.shape  # n-rows, m-columns

# Έλεγχος στην περίπτωση που ο πίανακς δεν είναι τετραγωνικός

if n!=m: print('Ο πίνακας Α δεν είναι τετραγωνικός')
print(A)
print('Ο πίνακας b έχει %d γραμμές και %d στήλες'%b.shape)
print(b)


C = np.concatenate((A,b), axis = 1)     # Σχηματισμός του επαυξημένου πίνακα
print('Ο επαυξημένος πίνακας C έχει %d γραμμές και %d στήλες'%C.shape)
print(C) 

[[ 1.  2.  1.]
 [ 2.  2.  3.]
 [-1. -3.  0.]]
Ο πίνακας b έχει 3 γραμμές και 1 στήλες
[[0.]
 [3.]
 [2.]]
Ο επαυξημένος πίνακας C έχει 3 γραμμές και 4 στήλες
[[ 1.  2.  1.  0.]
 [ 2.  2.  3.  3.]
 [-1. -3.  0.  2.]]


In [4]:
# Η διαδικασία της επίλυσης (γραμμοπράξεις) γίνεται χειροκίνητα, και όχι υπολογιστικά (στον κώδικα που κάνουμε με μερική οδήγηση δείχνουμε με ποιόν τρόπο οι γραμμοπράξεις γίνονται υπολογιστικά και όχι αναλυτικά)

# Θυμόμαστε ότι η αρίθμηση των γραμμών ξεκινά απ'το 0, επομένως C[1] είναι η δεύτερη γραμμή του επαυξημένου πίνακα, δηλαδή η [2. 2. 3. 3.]

C[1] = C[1] - 2*C[0]
print(C)


[[ 1.  2.  1.  0.]
 [ 0. -2.  1.  3.]
 [-1. -3.  0.  2.]]


In [5]:
C[2] = C[2] + C[0]
print(C)

[[ 1.  2.  1.  0.]
 [ 0. -2.  1.  3.]
 [ 0. -1.  1.  2.]]


In [6]:
C[2] = C[2] - 0.5*C[1]
print(C)

[[ 1.   2.   1.   0. ]
 [ 0.  -2.   1.   3. ]
 [ 0.   0.   0.5  0.5]]


In [7]:
# Αφού έγιναν οι γραμμοπράξεις που φαίρνουν τον πίνακα Α σε άνω τριγωνική μορφή μένει να γίνει η πίσω αντικατάσταση.

x3 = C[2,3] / C[2,2]
x2 = (C[1,3] - x3*C[1,2]) / C[1,1]
x1 = (C[0,3] - x2*C[0,1] - x3*C[0,2])/C[0,0]

In [8]:
X = np.array([[x1], [x2], [x3]])
print(X)

[[ 1.]
 [-1.]
 [ 1.]]


In [9]:
# Σαν επιβεβαίωση της λύσης ελέγχουμε αν πράγματι ισχύει Α x - b = 0

print(A@X - b) # A@X, is the dot product of the two matrices A and X

[[0.]
 [0.]
 [0.]]
