In [5]:
import numpy as np

In [6]:
A = np.array([ [1. ,2. , 1. ], 
               [2. ,2. , 3. ], 
               [-1., -3., 0.] ])

b = np.array([ [0.],   # note the format of np.array([ ])
               [3.],   # np.array([ [0], [3], [2] ]) has shape 3 x 1 (πίνακας στήλη)
               [2.] ]) # while np.array([[ 0, 3, 2 ]) would have 1 x 3 (πίνακας γραμμή)

C = np.concatenate((A,b), axis = 1)  # Σχηματισμός του επαυξημένου πίνακα

In [7]:
# Αν θέλω μερική οδήγηση εναλλάσσω τις γραμμές του πίνακα, προκειμένου το 1ο στοιχείο της 1ης γραμμής να είναι το μεγαλύτερο κατ' απόλυτη τιμή από το 1ο στοιχείο όλων των υπόλοιπων γραμμών


print('Ξεκινά η επίλυση με μέθοδο απαλοιφής Gauss με χρήση μερικής οδήγησης \n')
isSolvable = True    # Η μεταβλητή flag αυτή θα μου σταματά το πρόγραμμα αν έχω κάποιο μηδενισμό
for row in range(C.shape[0]):
  col = row          # Διαγώνια στοιχεία
  pivotRow = row + np.argmax(abs(C[row:, col]))  # Ψάχνω το μέγιστο στοιχείο μέσα στον εκάστοτε υποπίνακα. Ο συμβολισμός row: σημαίνει απ'την τρέχουσα γραμμή ως την τελευταία όπου η στήλη ορίζεται απ'το col (π.χ. η εντολή αυτή για row=2 πάει στην 3η στήλη και αναζητά ποιά γραμμή έχει το μεγαλύτερο κατ' απόλυτη τιμή αριθμό)
  C[[row, pivotRow]] = C[[pivotRow, row]]        # Εδώ γίνεται η εναλλαγή γραμμών
  pivotEle = C[row , col]                        # Εδώ ορίζεται το στοιχείο οδηγός
  if pivotEle == 0:         # Αν το στοιχείο οδηγός είναι μηδενικό τότε το σύστημα δεν επιλύεται
    print('Το σύστημα δεν επιλύεται')
    isSolvable = False
    break
  else:   # Όταν είναι μή μηδενικό υπολογίζει το συντελεστή m που θα πολλαπλασιάσει την εκάστοτε γραμμή με τη γραμμή του στοιχείου οδηγού και θα την αθροίση στην εκάστοτε γραμμή (γραμμοπράξεις)
    for r in range(row+1, C.shape[0] ):
      m =  - (C[r,col] / pivotEle) 
      C[r] = C[r] + m*C[row] 

if(isSolvable):
  print('Ο πίνακάς μας έχει έρθει σε άνω διαγώνια μορφή \n', C)
  print('Ορίζω το διάνυσμα της λύσης και το αρχικοποιώ να έχει το σχήμα του C με μηδενικά στοιχεία')
  X = np.array([[0.] for ii in range(C.shape[0])])  # Ορίζω το διάνυσμα της λύσης και το αρχικοποιώ να έχει το σχήμα του C με μηδενικά στοιχεία
  print(X)

Ξεκινά η επίλυση με μέθοδο απαλοιφής Gauss με χρήση μερικής οδήγησης 

Ο πίνακάς μας έχει έρθει σε άνω διαγώνια μορφή 
 [[ 2.    2.    3.    3.  ]
 [ 0.   -2.    1.5   3.5 ]
 [ 0.    0.    0.25  0.25]]
Ορίζω το διάνυσμα της λύσης και το αρχικοποιώ να έχει το σχήμα του C με μηδενικά στοιχεία
[[0.]
 [0.]
 [0.]]


In [8]:
# Εδώ γίνεται η πίσω αντικατάσταση


for ii in reversed(range(len(X))): # Reversed γιατί ξεκινάω απ' το x3 και αντικαθιστώ προς τα πίσω μέχρι το x1
    X[ii] = ( C[ii,-1] - C[ii][:-1]@(X) ) / C[ii,ii]
# Ξεκινάει για τον επαυξημένο μας πίνακα (3x4) από την τελευταία γραμμή προς την πρώτη (αυτό κάνει το loop) και παίρνει το "επαυξημένο" στοιχείο της εκάστοτε γραμμής και αφαιρεί από αυτό όσα στοιχεία μεσολαβούν επί τα αντίστοιχα Χ[ι] μέχρι να φτάσουμε στο υπό μελέτη στοιχείο
# Δηλαδή X[2]=(C23/C22), X[1]=(C13-C12X[2])/C11, X[0]=(C03-C02X[2]-C01X[1])/C00
print('Η λύση βρίσκεται να είναι \n', X)
print('Επαληθεύουμε τη λύση')
print('A X - b = \n', A@X - b )

Η λύση βρίσκεται να είναι 
 [[ 1.]
 [-1.]
 [ 1.]]
Επαληθεύουμε τη λύση
A X - b = 
 [[0.]
 [0.]
 [0.]]
