In [1]:
import numpy as np

In [9]:
# Επαναληπτική Μέθοδος Jacobi

def Jacobi(A, b): 
    (n, m) = A.shape
    if n != m: print('Ο πίνακας δεν είναι τετραγωνικός, αλλά %d x %d'%(n, m))
    if (n, 1) != b.shape: print('Το b δεν είναι διάνυσμα στήλης ίδιας διάστασης με τον Α')
  
    D = np.identity(n)                # Αρχικοποιώ τον D ως τον μοναδιαίο πίνακα
    Dinv = np.identity(n)             # Παίρνω τον αντίστροφό του, D^{-1}
    for k in range(n): 
        D[k,k] = A[k,k]               # Εκχωρώ στα στοιχεία της διαγωνίου τα στοιχεία της 
        Dinv[k,k] = 1/A[k,k]          # διαγωνίου του Α για τους D, D^{-1}

    S = D - A                         # Σπάμε τον πίνακα Α σε διαφορά πινάκων A = D - S (ο D περιέχει τα στοιχεία της διαγωνίου του Α και όλα τα μη διαγώνια στοιχεία μηδενικά, ενώ ο S έχει όλα τα μη διαγώνια στοιχεία του Α με αντίθετο πρόσημο, προκειμένου να είναι A = D - S)
    M = Dinv@S                        # Ορίζω τον Μ = D^{-1}*S
    Dinvb = Dinv@b                    # Ορίζω την ποσότητα D^{-1}*b
    print('M \n', M)
    X = np.zeros((n,1))               # Αρχικοποίηση της λύσης (μηδενικός πίνακας στήλη)

    for ii in range(100): 
        X = M@X + Dinvb               # Εδώ είναι το αποτέλεσμα x_{n+1} = M*x_{n} + D^{-1}*b

    print('Τελικός X \n', X)
    print('Τελικά Ax - b \n', A@X - b)





if __name__ == '__main__':            # Κυρίως πρόγραμμα που δίνω τους πίνακες A, b
    b = np.array([ [10.], 
                   [5.],   
                   [10.] ]) 

    A = np.array([ [ 3  , -1. ,  0 ], 
                   [-1. ,  3. , -1 ], 
                   [0   , -2. , 4. ] 
                ])
        
    Jacobi(A, b)                      # Καλώ την Jacobi με ορίσματα τους πίνακες του συστήματος που καλούμαι να επιλύσω 

M 
 [[0.         0.33333333 0.        ]
 [0.33333333 0.         0.33333333]
 [0.         0.5        0.        ]]
Τελικός X 
 [[5.]
 [5.]
 [5.]]
Τελικά Ax - b 
 [[0.]
 [0.]
 [0.]]


In [10]:
# Επαναληπτική Μέθοδος Gauss Seidel (δεν χρησιμοποιώ τον D^{-1})

def GaussSeidel(A, b):
    '''Επαναληπτική μέθοδος Gauss Seidel με διαδοχικές αντικαταστάσεις''' 
    (n, m) = A.shape
    if n != m: print('Ο πίνακας δεν είναι τετραγωνικός, αλλά %d x %d'%(n, m))
    if (n, 1) != b.shape: print('Το b δεν είναι διάνυσμα στήλης ίδιας διάστασης με τον Α')
  


    X = np.zeros((n,1))                 # Αρχικοποίηση της λύσης (μηδενικός πίνακας στήλη)
    
    for ii in range(100):
      for row in range(n):
        U = X.copy()                    # Κατασκευάζω έναν κλώνο του Χ 
        U[row] = 0                      # Του δίνω μηδενικά στοιχεία στην εκάστοτε γραμμή
        X[row] = (b[row] - A[row]@U)/A[row, row] 
 
    print('Τελική λύση X \n', X)
    print('Τελικά Ax - b \n', A@X - b)



if __name__ == '__main__':               # Κυρίως πρόγραμμα που δίνω τους πίνακες A, b
    
    b = np.array([ [10.], 
                   [5.],   
                   [10.] ]) 

    A = np.array([ [ 1  , -1. ,  0 ], 
                   [-1. ,  3. , -1 ], 
                   [0   , -2. , 4. ] 
                ])
    
    GaussSeidel(A, b)

Τελική λύση X 
 [[21.66666667]
 [11.66666667]
 [ 8.33333333]]
Τελικά Ax - b 
 [[-1.77635684e-15]
 [ 3.55271368e-15]
 [-3.55271368e-15]]


In [11]:
# Ένας εξτρα έλεγχος για τη μέθοδο


def linSysIterMatrixFormat(A, b):
    ''' Gauss Seidel in matrix format ala text book 
       -- requires lower diagonal matrix inversion -- 
       performed here with numpy for cross check'''

    (n, m) = A.shape
    if n != m: print('A is not a square matrix but is %d x %d'%(n, m))
    if (n, 1) != b.shape: print('b is not a column vector of same dim as A')

    D = np.tril(A)
    S = - np.triu(A, k=1)
    Dinv = np.linalg.inv(D) # small cheating
    M = Dinv@S
    Dinvb = Dinv@b

    w, v = np.linalg.eig(M)
    print('M \n', M)
    print('eigenvalues \n', w)
    print('eigenvectors \n', v)
    print('spectral radius = ', max(abs(w)))

    X = np.zeros((n,1))  

    for ii in range(100): 
        X = M@X + Dinvb 

    print('cross-checked X \n', X)
    print('cross-checked Ax - b \n', A@X - b)

linSysIterMatrixFormat(A, b) # this is for cross-check

M 
 [[0.         1.         0.        ]
 [0.         0.33333333 0.33333333]
 [0.         0.16666667 0.16666667]]
eigenvalues 
 [0.  0.5 0. ]
eigenvectors 
 [[ 1.00000000e+000  8.72871561e-001  1.00000000e+000]
 [ 0.00000000e+000  4.36435780e-001 -3.00625254e-292]
 [ 0.00000000e+000  2.18217890e-001  3.00625254e-292]]
spectral radius =  0.5
cross-checked X 
 [[21.66666667]
 [11.66666667]
 [ 8.33333333]]
cross-checked Ax - b 
 [[ 0.00000000e+00]
 [-3.55271368e-15]
 [ 0.00000000e+00]]
