In [1]:
# Διάσπαση του πίνακα Α σε γινόμενο πινάκων LU

import numpy as np
A = np.array([ [1. ,2. , 1. ], 
               [2. ,2. , 3. ], 
               [-1., -3., 0.] ])

print('Ξεκινάμε την παραγοντοποίηση LU \n')
(n,m) = A.shape
if n != m: print('Ο πίνακας Α δεν είναι τετραγωνικός')

# Σχηματισμός των U, L
U = A.copy()  # Αυτό δεν είναι απαραίτητο, είναι πιο αποδοτικό να αποθηκεύονται οι L, U εντός του Α
L = np.identity(A.shape[0])

print('Αρχικοποίηση του πίνακα U σε \n', U)
print('Αρχικοποίηση του πίνακα L σε \n', L)

for k in range(n-1):
    for j in range(k+1,n):
        L[j,k] = U[j,k] / U[k,k]
        U[j,k:n] = U[j,k:n] - L[j,k]*U[k,k:n]

print('Τελική μορφή του L \n', L)
print('Τελική μορφή του U \n', U)

print('Επαληθεύουμε ότι ο LU-A είναι ο μηδενικός πίνακας \n', L@U - A)

Ξεκινάμε την παραγοντοποίηση LU 

Αρχικοποίηση του πίνακα U σε 
 [[ 1.  2.  1.]
 [ 2.  2.  3.]
 [-1. -3.  0.]]
Αρχικοποίηση του πίνακα L σε 
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Τελική μορφή του L 
 [[ 1.   0.   0. ]
 [ 2.   1.   0. ]
 [-1.   0.5  1. ]]
Τελική μορφή του U 
 [[ 1.   2.   1. ]
 [ 0.  -2.   1. ]
 [ 0.   0.   0.5]]
Επαληθεύουμε ότι ο LU-A είναι ο μηδενικός πίνακας 
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [2]:
# Εμπρός και πίσω αντικατάσταση για επίλυση συστήματος Ax=b, εφόσον έχουμε σπάσει τον Α σε γινόμενο LU (Α είναι ο πίνακας που διασπάσαμε)

b = np.array([ [0.],   
               [3.],  
               [2.] ])


# Εμπρός αντικατάσταση (Ly=x)

C = np.concatenate((L,b), axis = 1)
print('Παίρνουμε τον επαυξημένο του U \n', C)
print('Ορίζω το διάνυσμα της λύσης και το αρχικοποιώ να έχει το σχήμα του C (επαυξημένου) με μηδενικά στοιχεία')
Y = np.array([[0.] for ii in range(C.shape[0])]) 
print(Y)

# Εδώ γίνεται η εμπρός αντικατάσταση
for ii in range(len(Y)): 
    Y[ii] = ( C[ii,-1] - C[ii][:-1]@(Y) ) / C[ii,ii]

print('Η λύση βρίσκεται να είναι \n', Y)






# Πίσω αντικατάσταση (Ux=y)

D = np.concatenate((U,Y), axis = 1)
print('Παίρνουμε τον επαυξημένο του U \n', D)
print('Ορίζω το διάνυσμα της λύσης και το αρχικοποιώ να έχει το σχήμα του D (επαυξημένου) με μηδενικά στοιχεία')
X = np.array([[0.] for ii in range(D.shape[0])]) 
print(X)

# Εδώ γίνεται η πίσω αντικατάσταση
for ii in reversed(range(len(X))): 
    X[ii] = ( D[ii,-1] - D[ii][:-1]@(X) ) / D[ii,ii]

print('Η λύση βρίσκεται να είναι \n', X)
print('Επαληθεύουμε τη λύση (U X - Y = 0)')
print('U X - Y = \n', U@X - Y )

Παίρνουμε τον επαυξημένο του U 
 [[ 1.   0.   0.   0. ]
 [ 2.   1.   0.   3. ]
 [-1.   0.5  1.   2. ]]
Ορίζω το διάνυσμα της λύσης και το αρχικοποιώ να έχει το σχήμα του C (επαυξημένου) με μηδενικά στοιχεία
[[0.]
 [0.]
 [0.]]
Η λύση βρίσκεται να είναι 
 [[0. ]
 [3. ]
 [0.5]]
Παίρνουμε τον επαυξημένο του U 
 [[ 1.   2.   1.   0. ]
 [ 0.  -2.   1.   3. ]
 [ 0.   0.   0.5  0.5]]
Ορίζω το διάνυσμα της λύσης και το αρχικοποιώ να έχει το σχήμα του D (επαυξημένου) με μηδενικά στοιχεία
[[0.]
 [0.]
 [0.]]
Η λύση βρίσκεται να είναι 
 [[ 1.]
 [-1.]
 [ 1.]]
Επαληθεύουμε τη λύση (U X - Y = 0)
U X - Y = 
 [[0.]
 [0.]
 [0.]]
